title: ak_site
description: "ak_site"
baseurl: ""
url: ""
tagline: "||||||||||||||||||||||"
category: ""
collection: ""

# Build settings
plugins:
  - jekyll-feed
  - jekyll-paginate
markdown: kramdown
kramdown:
    auto_ids: false
paginator: enable
paginate: 200
paginate_path: '/blog/page:num/'
permalink: /blog/:categories/:year/:title/

