title: ak_site
description: "ak_site"
baseurl: ""
url: ""
tagline: "||||||||||||||||||||||"
category: ""
collection: ""

# Build settings
plugins:
  - jekyll-feed
  - jekyll-paginate
markdown: kramdown
kramdown:
    auto_ids: false
paginator: enable
paginate: 10
paginate_path: '/blog/page:num/'
permalink: /blog/:categories/:year/:title/

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
